import request from '@/utils/request'
const api = '/api/ai/inspection'
export const inspectionOverview = () => request({ url: `${api}/overview` })
export const inspectionHealth = () => request({ url: `${api}/health` })
export const inspectionAnalytics = days => request({ url: `${api}/analytics`, params: { days } })
export const inspectionPlans = params => request({ url: `${api}/plans`, params })
export const inspectionTasks = params => request({ url: `${api}/tasks`, params })
export const inspectionResults = params => request({ url: `${api}/results`, params })
export const reviewInspectionResult = (id, status, note) => request({ url: `${api}/results/${id}/review`, method: 'post', params: { status, note } })
export const inspectionWorkOrders = () => request({ url: `${api}/work-orders` })
export const acceptWorkOrder = id => request({ url: `${api}/work-orders/${id}/accept`, method: 'post' })
export const resolveWorkOrder = (id, resolution) => request({ url: `${api}/work-orders/${id}/resolve`, method: 'post', params: { resolution } })
export const verifyWorkOrder = (id, passed) => request({ url: `${api}/work-orders/${id}/verify`, method: 'post', params: { passed } })
export const sceneTemplates = () => request({ url: `${api}/scene-templates` })
export const sceneRegions = id => request({ url: `${api}/scene-templates/${id}/regions` })
export const algorithms = () => request({ url: `${api}/algorithms` })
export const algorithmEvents = () => request({ url: `${api}/algorithm-events` })
export const reviewAlgorithmEvent = (id, status) => request({ url: `${api}/algorithm-events/${id}/review`, method: 'post', params: { status } })
export const sceneRisk = () => request({ url: `${api}/scene-risk` })
export const maintenanceWindows = () => request({ url: `${api}/maintenance-windows` })
export const mobileRecorders = () => request({ url: `${api}/mobile-recorders` })
export const createMobileRecorder = data => request({ url: `${api}/mobile-recorders`, method: 'post', data })
export const recorderLocations = id => request({ url: `${api}/mobile-recorders/${id}/locations` })
export const storeVisits = () => request({ url: `${api}/store-visits` })
export const createStoreVisit = data => request({ url: `${api}/store-visits`, method: 'post', data })
export const visitCheckResults = id => request({ url: `${api}/store-visits/${id}/check-results` })
export const visitMedia = id => request({ url: `${api}/store-visits/${id}/media` })
export const rectifications = () => request({ url: `${api}/store-visits/rectifications` })
export const reviewRectification = (id, passed, note) => request({ url: `${api}/store-visits/rectifications/${id}/review`, method: 'post', params: { passed, note } })
export const visitOperations = days => request({ url: `${api}/store-visits/operations`, params: { days } })
