<template>
  <view class="page">
    <view class="selector">
      <text class="section-title">选择收藏通道</text>
      <scroll-view scroll-x class="channels"><view class="channel-row"><view v-for="item in monitor.favorites" :key="item.deviceId+item.channelId" class="channel" :class="selected?.channelId===item.channelId?'active':''" @click="selected=item"><text>{{item.name}}</text></view></view></scroll-view>
      <EmptyState v-if="!monitor.favorites.length" title="尚无收藏通道" description="请先在实时预览页面收藏通道"/>
      <view v-if="monitor.favorites.length" class="date-row"><picker mode="date" :value="date" @change="changeDate"><view class="date">{{date}}⌄</view></picker><button class="query" size="mini" @click="query">查询录像</button></view>
    </view>
    <view v-if="records.length" class="list"><view v-for="(item,index) in records" :key="index" class="card" @click="play(item)"><view class="card__top"><text class="card__title">{{item.name||`录像 ${index+1}`}}</text><text class="record-type">{{item.type||'录像'}}</text></view><text class="card__meta">开始：{{item.startTime||'-'}}\n结束：{{item.endTime||'-'}}\n点击开始回放</text></view></view>
    <EmptyState v-else-if="queried&&!loading" title="没有查询到录像"/><view v-if="loading" class="loading">正在查询设备录像…</view>
  </view>
</template>
<script setup lang="ts">
import{ref}from'vue';import{onShow}from'@dcloudio/uni-app';import EmptyState from'@/components/EmptyState.vue';import{useMonitorStore,type ChannelShortcut}from'@/stores/monitor';import{queryGbRecords,type RecordItem}from'@/api/record';import{showRequestError}from'@/utils/request';import{useAuthStore}from'@/stores/auth'
const auth=useAuthStore(),monitor=useMonitorStore(),selected=ref<ChannelShortcut>(),records=ref<RecordItem[]>([]),loading=ref(false),queried=ref(false);const now=new Date();const date=ref(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`);function changeDate(e:any){date.value=e.detail.value;records.value=[];queried.value=false}function play(item:RecordItem){if(!selected.value||!item.startTime||!item.endTime)return;uni.navigateTo({url:`/pages/record/playback?deviceId=${encodeURIComponent(selected.value.deviceId)}&channelId=${encodeURIComponent(selected.value.channelId)}&name=${encodeURIComponent(selected.value.name)}&startTime=${encodeURIComponent(item.startTime)}&endTime=${encodeURIComponent(item.endTime)}`})}async function query(){if(!selected.value)return uni.showToast({title:'请选择通道',icon:'none'});loading.value=true;queried.value=true;try{const r=await queryGbRecords(selected.value.deviceId,selected.value.channelId,`${date.value} 00:00:00`,`${date.value} 23:59:59`);records.value=r.recordList||r.list||[]}catch(e){showRequestError(e)}finally{loading.value=false}}onShow(()=>{if(auth.requireAuth()){monitor.restore();selected.value=selected.value||monitor.favorites[0]}})
</script>
<style lang="scss" scoped>@use '@/styles/list.scss';.selector{padding:28rpx 24rpx;background:#fff}.section-title{font-size:30rpx;font-weight:600}.channels{margin-top:22rpx;white-space:nowrap}.channel-row{display:flex;gap:14rpx}.channel{flex:none;padding:18rpx 24rpx;color:#667085;background:#f2f4f8;border-radius:16rpx;font-size:24rpx}.active{color:#fff;background:#2368f2}.date-row{display:flex;align-items:center;justify-content:space-between;margin-top:28rpx}.date{padding:18rpx 24rpx;background:#f2f4f8;border-radius:16rpx;font-size:25rpx}.query{margin:0;color:#fff;background:#2368f2}.record-type{color:#2368f2;font-size:22rpx}.loading{padding:80rpx;text-align:center;color:#8992a6;font-size:25rpx}</style>
