<template><view class="page"><view class="player"><video v-if="url" class="video" :src="url" autoplay controls object-fit="contain" @play="state='playing'" @waiting="state='connecting'" @error="videoError"/><view v-else class="placeholder"><text>{{ stateText }}</text><button v-if="state==='error'" class="retry" @click="retry">重新连接</button></view><text class="state">{{ stateText }}</text></view><view class="panel"><view class="title-row"><text class="title">{{ name||channelId }}</text><button class="favorite" size="mini" @click="toggleFavorite">{{ isFavorite?'已收藏':'收藏' }}</button></view><text class="meta">设备：{{ deviceId }}\n通道：{{ channelId }}</text>
<view class="ptz"><text class="section-title">云台控制</text><view class="ptz-grid"><view/><button class="ptz-btn" @touchstart="move('up')" @touchend="move('stop')">↑</button><view/><button class="ptz-btn" @touchstart="move('left')" @touchend="move('stop')">←</button><button class="ptz-btn stop-btn" @click="move('stop')">停</button><button class="ptz-btn" @touchstart="move('right')" @touchend="move('stop')">→</button><view/><button class="ptz-btn" @touchstart="move('down')" @touchend="move('stop')">↓</button><view/></view><view class="zoom"><button class="zoom-btn" @touchstart="move('zoomout')" @touchend="move('stop')">变倍 −</button><button class="zoom-btn" @touchstart="move('zoomin')" @touchend="move('stop')">变倍 ＋</button></view></view>
<view v-if="url" class="protocol"><text>当前播放地址</text><text class="url">{{ url }}</text></view><button class="stop" @click="stopAndBack">停止播放</button></view></view></template>
<script setup lang="ts">
import {computed,ref} from 'vue'; import {onLoad,onUnload,onHide} from '@dcloudio/uni-app'; import {startPlay,stopPlay,chooseH5Stream} from '@/api/play'; import {controlPtz,type PtzCommand} from '@/api/ptz'; import {useMonitorStore} from '@/stores/monitor'; import {showRequestError} from '@/utils/request'
const monitor=useMonitorStore();const deviceId=ref('');const channelId=ref('');const name=ref('');const url=ref('');const state=ref<'loading'|'connecting'|'playing'|'error'>('loading');let stopped=false
const stateText=computed(()=>({loading:'正在请求视频流…',connecting:'正在连接…',playing:'播放中',error:'播放失败'}[state.value]));const isFavorite=computed(()=>monitor.isFavorite(deviceId.value,channelId.value))
async function start(){state.value='loading';stopped=false;try{const stream=await startPlay(deviceId.value,channelId.value);url.value=chooseH5Stream(stream);if(!url.value)throw new Error('后端未返回 H5 可播放的 HLS/WebRTC 地址');state.value='connecting'}catch(e){state.value='error';showRequestError(e)}}
async function stop(){if(stopped||!deviceId.value)return;stopped=true;try{await stopPlay(deviceId.value,channelId.value)}catch{}}
async function stopAndBack(){await stop();uni.navigateBack()} function videoError(){state.value='error';url.value='';uni.showToast({title:'当前浏览器无法播放该视频流',icon:'none'})}async function retry(){await stop();await start()}
function toggleFavorite(){monitor.toggleFavorite({deviceId:deviceId.value,channelId:channelId.value,name:name.value||channelId.value,lastViewedAt:Date.now()});uni.showToast({title:isFavorite.value?'已收藏':'已取消收藏',icon:'none'})}
async function move(command:PtzCommand){try{await controlPtz(deviceId.value,channelId.value,command)}catch(e){showRequestError(e)}}
onLoad((q)=>{monitor.restore();deviceId.value=String(q?.deviceId||'');channelId.value=String(q?.channelId||'');name.value=String(q?.name||'');monitor.addRecent({deviceId:deviceId.value,channelId:channelId.value,name:name.value||channelId.value,lastViewedAt:Date.now()});start()});onHide(stop);onUnload(stop)
</script>
<style scoped>
.page{min-height:100vh;background:#10131a}.player{position:relative;width:100%;aspect-ratio:16/9;background:#050608}.video,.placeholder{width:100%;height:100%}.placeholder{display:flex;align-items:center;justify-content:center;flex-direction:column;color:#8f98aa;font-size:26rpx}.retry{margin-top:24rpx;color:#fff;background:#2368f2;font-size:24rpx}.state{position:absolute;top:18rpx;left:18rpx;padding:6rpx 14rpx;color:#fff;background:rgba(0,0,0,.55);border-radius:999rpx;font-size:20rpx}.panel{margin-top:20rpx;padding:32rpx;color:#eaf0ff;background:#191e29}.title-row{display:flex;align-items:center;justify-content:space-between}.title{display:block;font-size:34rpx;font-weight:600}.favorite{margin:0;color:#2368f2;background:#eaf1ff}.meta{display:block;margin-top:18rpx;color:#9da7bb;font-size:24rpx;line-height:1.8}.section-title{display:block;margin:30rpx 0 20rpx;font-size:28rpx;font-weight:600}.ptz-grid{width:330rpx;margin:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:12rpx}.ptz-btn{width:100rpx;height:76rpx;margin:0;color:#eaf0ff;background:#2a3242;line-height:76rpx}.stop-btn{color:#ffb4b4}.zoom{display:flex;gap:18rpx;margin-top:18rpx}.zoom-btn{flex:1;color:#eaf0ff;background:#2a3242}.protocol{margin-top:30rpx;padding:22rpx;background:#11151d;border-radius:18rpx;color:#aeb7c8;font-size:23rpx}.url{display:block;margin-top:12rpx;word-break:break-all;color:#73809a}.stop{margin-top:40rpx;color:#fff;background:#d94b4b;border-radius:18rpx}
</style>
