<template><div class="app-container"><div class="head"><h2>场景与算法运营</h2><el-button @click="load">刷新</el-button></div>
<el-tabs v-model="tab">
<el-tab-pane label="场景模板" name="scenes"><el-table :data="scenes" border><el-table-column prop="name" label="模板"/><el-table-column prop="code" label="编码"/><el-table-column prop="description" label="说明"/><el-table-column prop="status" label="状态"/></el-table></el-tab-pane>
<el-tab-pane label="算法管理" name="algorithms"><el-table :data="algorithmList" border><el-table-column prop="name" label="算法"/><el-table-column prop="category" label="分类"/><el-table-column prop="confidenceThreshold" label="置信度"/><el-table-column prop="riskLevel" label="风险"/><el-table-column label="状态"><template slot-scope="{row}"><el-tag :type="row.enabled?'success':'info'">{{row.enabled?'启用':'停用'}}</el-tag></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="算法事件" name="events"><el-table :data="events" border><el-table-column prop="algorithmCode" label="算法"/><el-table-column prop="channelId" label="通道"/><el-table-column prop="confidence" label="置信度"/><el-table-column prop="state" label="状态"/><el-table-column prop="createTime" label="时间"/><el-table-column label="复核" width="180"><template slot-scope="{row}"><span v-if="row.reviewStatus!=='PENDING'">{{row.reviewStatus}}</span><template v-else><el-button size="mini" type="danger" @click="review(row,'CONFIRMED')">确认</el-button><el-button size="mini" @click="review(row,'FALSE_POSITIVE')">误报</el-button></template></template></el-table-column></el-table></el-tab-pane>
<el-tab-pane label="维护时段" name="maintenance"><el-table :data="windows" border><el-table-column prop="scopeType" label="范围"/><el-table-column prop="scopeId" label="对象"/><el-table-column prop="startTime" label="开始"/><el-table-column prop="endTime" label="结束"/><el-table-column prop="reason" label="原因"/></el-table></el-tab-pane>
<el-tab-pane label="场景风险" name="risk"><el-table :data="risks" border><el-table-column prop="templateName" label="场景"/><el-table-column prop="riskScore" label="积分"/><el-table-column prop="riskLevel" label="等级"/><el-table-column prop="openCount" label="待处理"/><el-table-column prop="falsePositiveCount" label="误报"/></el-table></el-tab-pane>
</el-tabs></div></template>
<script>import {sceneTemplates,algorithms,algorithmEvents,reviewAlgorithmEvent,maintenanceWindows,sceneRisk} from '@/api/inspection'
const data=v=>(v&&v.data)||v||[];export default{name:'SceneAlgorithms',data:()=>({tab:'scenes',scenes:[],algorithmList:[],events:[],windows:[],risks:[]}),created(){this.load()},methods:{async load(){const r=await Promise.all([sceneTemplates(),algorithms(),algorithmEvents(),maintenanceWindows(),sceneRisk()]);this.scenes=data(r[0]);this.algorithmList=data(r[1]);this.events=data(r[2]);this.windows=data(r[3]);this.risks=data(r[4])},async review(row,status){await reviewAlgorithmEvent(row.id,status);this.load()}}}</script>
<style scoped>.head{display:flex;justify-content:space-between;align-items:center}.head h2{margin-top:0}</style>
